language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
install:
  - git clone https://github.com/sstephenson/bats.git && cd bats && ./install.sh .. && cd -
  - pip install -U pip setuptools
  - pip install -U . -r dev-requirements.txt
# command to run tests
script:
  - paver lint
  - paver coverage
  - PATH=$PWD/bin:$PATH paver bats

addons:
  code_climate:
    repo_token: 184a6ec8293cad700aa6dd0076d3d7296b25a7b432717acfbff3053dc7cce88a
